version: '3'
services:
  app:
    build: .
    ports:
      - "3333:80" # Change this to "80:80" for production deployment
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_URI=mongodb://localhost:27017/mydatabase
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
